### ISSUE TITLE
这个难道不是慕课网上廖师兄的代码

### ISSUE THREAD

**Issue by cryhac** [sqmax/springboot-project#4]
这个难道不是慕课网上廖师兄的代码？

**Comment by sqmax** [comment]
估计你是没有fork+learning的习惯，也不会利用开源和学习。

**Comment by cryhac** [comment]
你这个是fork吗？哈哈哈哈。。。。。

**Comment by sqmax** [comment]
不是了，项目是自己看学习时一行一行敲下来并调试的。
就是觉得你否定别人劳动成果的话挺让人生气。
