### ISSUE TITLE
访问前端界面问题

### ISSUE THREAD

**Issue by boonguan** [sqmax/springboot-project#8]
按照您的步骤配置了之后，访问http://127.0.0.1只显示页面的框架没有商品内容，结果如截图所示：
![image](https://user-images.githubusercontent.com/36440177/52624419-a7dc4880-2ee9-11e9-9067-facc63031b42.png)
请问您知道这种情况是哪里出了问题吗？谢谢

**Comment by sqmax** [comment]
你后端项目没启动吧，它是要向后端取数据的。
